config/routes.rb
Rails.application.routes.draw do
	
  resources :points
  resources :cities
  resources :contacts
	devise_for :admins
	resources :metatags
	resources :photos
	resources :tours
	root to: 'pages#index'

	get 'closed' => 'pages#closed', as: :closed
	get 'index' => 'pages#index', as: :index
	get 'populars' => 'pages#populars', as: :populars
	get 'results' => 'pages#results', as: :results
	get 'order-form' => 'pages#orderForm', as: :orderForm
	get 'admin' => 'pages#admin', as: :admin
	get 'franchise' => 'pages#landing', as: :franchise
	resources :comments, only: [:new, :create]	
	resources :selections, only: [:new, :create]	

	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/point.rb
class Point < ApplicationRecord
  belongs_to :city
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_point, only: [:show, :edit, :update, :destroy]
  layout "admin"

  # GET /points
  # GET /points.json
  def index
    @points = Point.order(title: :asc)
  end

  # GET /points/1
  # GET /points/1.json
  def show
  end

  # GET /points/new
  def new
    @point = Point.new
  end

  # GET /points/1/edit
  def edit
  end

  # POST /points
  # POST /points.json
  def create
    @point = Point.new(point_params)

    respond_to do |format|
      if @point.save
        format.html { redirect_to points_url, notice: 'Point was successfully created.' }
        format.json { render :show, status: :created, location: @point }
      else
        format.html { render :new }
        format.json { render json: @point.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /points/1
  # PATCH/PUT /points/1.json
  def update
    respond_to do |format|
      if @point.update(point_params)
        format.html { redirect_to points_url, notice: 'Point was successfully updated.' }
        format.json { render :show, status: :ok, location: @point }
      else
        format.html { render :edit }
        format.json { render json: @point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /points/1
  # DELETE /points/1.json
  def destroy
    @point.destroy
    respond_to do |format|
      format.html { redirect_to points_url, notice: 'Point was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_point
      @point = Point.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def point_params
      params.require(:point).permit(:title, :phoneone, :phonetwo, :emailone, :emailtwo, :name, :address, :worktime, :city_id, :coming_soon)
    end
end

app/helpers/points_helper.rb
module PointsHelper
end

app/views/points/_form.html.erb
<%= form_with(model: point, local: true) do |form| %>
<% if point.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(point.errors.count, "error") %> prohibited this point from being saved:</h2>

  <ul>
    <% point.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>


<div class="row">
  <div class="col-lg-6">
    <%= form.text_field :title, class: "form-control admin__input", placeholder: "Название города", required: true %>
  </div>
  <div class="col-lg-6">
    <%= form.text_field :phoneone, class: "form-control admin__inputmargin--bottom-l margin--bottom-l", placeholder: "Номер телефона" %>
  </div>
  <div class="col-lg-6">
    <%= form.text_field :phonetwo, class: "form-control admin__input margin--bottom-l", placeholder: "Номер телефона 2" %>
  </div>
  <div class="col-lg-6">
    <%= form.collection_select :city_id, City.order(:title), :id, :title, { include_blank: "Выберите город" }, class: "form-control margin--bottom-l" %>
  </div>
  <div class="col-lg-6">
    <%= form.text_field :emailone, class: "form-control admin__input margin--bottom-l", placeholder: "Email 1" %>
  </div>
  <div class="col-lg-6">
    <%= form.text_field :emailtwo, class: "form-control admin__input margin--bottom-l", placeholder: "Email 2" %>
  </div>
  <div class="col-lg-6">
    <%= form.text_field :name, class: "form-control admin__input margin--bottom-l", placeholder: "Имя и Фамилия точки продаж" %>
  </div>
  <div class="col-lg-6">
    <%= form.text_field :address, class: "form-control admin__input margin--bottom-l", placeholder: "Адрес точки продаж" %>
  </div>
  <div class="col-lg-6">
    <%= form.text_field :worktime, class: "form-control admin__input margin--bottom-l", placeholder: "Рабочее время" %>
  </div>
  <div class="col-lg-6">

    <div class="form-check">
      <%= form.check_box :coming_soon, class: "form-check-input" %>
      <label class="form-check-label" for="defaultCheck1">
        Точка ожидает открытия?
      </label>
    </div>
    <p>
    </p>
  </div>

</div>

<div class="actions">
  <%= form.submit class: "admin__btn", value: "Добавить город" %>
</div>
<% end %>

app/views/points/edit.html.erb
<section class="admin">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="admin__h1">
          Редактировать точку продаж
        </h1>
      </div>
    </div>
    <%= render 'form', point: @point %>
  </div>
</section>

app/views/points/index.html.erb
<section class="admin">
  <div class="container">
    <div class="row">
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Город</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @points.each do |point| %>
          <tr>
            <td><%= point.title %></td>
            <td><%= point.address %></td>
            <td><%= point.name %></td>
            <td><%= point.city.title %></td>
            <td><%= link_to 'Редактировать', edit_point_path(point) %></td>
            <td><%= link_to 'Удалить', point, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

    </div>
    <div class="col-lg-12">
      <%= link_to 'Добавить точку продаж', new_point_path, class: "admin__btn" %>
    </div>
  </div>
</section>

app/views/points/new.html.erb
<section class="admin">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="admin__h1">
          Добавить точку продаж
        </h1>
      </div>
    </div>
    <%= render 'form', point: @point %>
  </div>
</section>

app/views/points/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @point.title %>
</p>

<p>
  <strong>Phoneone:</strong>
  <%= @point.phoneone %>
</p>

<p>
  <strong>Phonetwo:</strong>
  <%= @point.phonetwo %>
</p>

<p>
  <strong>Emailone:</strong>
  <%= @point.emailone %>
</p>

<p>
  <strong>Emailtwo:</strong>
  <%= @point.emailtwo %>
</p>

<p>
  <strong>Name:</strong>
  <%= @point.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @point.address %>
</p>

<p>
  <strong>Worktime:</strong>
  <%= @point.worktime %>
</p>

<%= link_to 'Edit', edit_point_path(@point) %> |
<%= link_to 'Back', points_path %>