config/routes.rb
Rails.application.routes.draw do
	
  resources :points
  resources :cities
  resources :contacts
	devise_for :admins
	resources :metatags
	resources :photos
	resources :tours
	root to: 'pages#index'

	get 'closed' => 'pages#closed', as: :closed
	get 'index' => 'pages#index', as: :index
	get 'populars' => 'pages#populars', as: :populars
	get 'results' => 'pages#results', as: :results
	get 'order-form' => 'pages#orderForm', as: :orderForm
	get 'admin' => 'pages#admin', as: :admin
	get 'franchise' => 'pages#landing', as: :franchise
	resources :comments, only: [:new, :create]	
	resources :selections, only: [:new, :create]	

	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/metatag.rb
class Metatag < ApplicationRecord
end

app/controllers/metatags_controller.rb
class MetatagsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_metatag, only: [:show, :edit, :update, :destroy]

  # GET /metatags
  # GET /metatags.json
  def index
    @metatags = Metatag.all
  end

  # GET /metatags/1
  # GET /metatags/1.json
  def show
  end

  # GET /metatags/new
  def new
    @metatag = Metatag.new
  end

  # GET /metatags/1/edit
  def edit
  end

  # POST /metatags
  # POST /metatags.json
  def create
    @metatag = Metatag.new(metatag_params)

    respond_to do |format|
      if @metatag.save
        format.html { redirect_to @metatag, notice: 'Metatag was successfully created.' }
        format.json { render :show, status: :created, location: @metatag }
      else
        format.html { render :new }
        format.json { render json: @metatag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /metatags/1
  # PATCH/PUT /metatags/1.json
  def update
    respond_to do |format|
      if @metatag.update(metatag_params)
        format.html { redirect_to @metatag, notice: 'Metatag was successfully updated.' }
        format.json { render :show, status: :ok, location: @metatag }
      else
        format.html { render :edit }
        format.json { render json: @metatag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /metatags/1
  # DELETE /metatags/1.json
  def destroy
    @metatag.destroy
    respond_to do |format|
      format.html { redirect_to metatags_url, notice: 'Metatag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_metatag
      @metatag = Metatag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def metatag_params
      params.require(:metatag).permit(:title, :keywords, :description, :page)
    end
end

app/helpers/metatags_helper.rb
module MetatagsHelper
end

app/views/metatags/_form.html.erb
<%= form_with(model: metatag, local: true) do |form| %>
  <% if metatag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(metatag.errors.count, "error") %> prohibited this metatag from being saved:</h2>

      <ul>
      <% metatag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :metatag_title %>
  </div>

  <div class="field">
    <%= form.label :keywords %>
    <%= form.text_field :keywords, id: :metatag_keywords %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :metatag_description %>
  </div>

  <div class="field">
    <%= form.label :page %>
    <%= form.text_field :page, id: :metatag_page %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/metatags/edit.html.erb
<h1>Editing Metatag</h1>

<%= render 'form', metatag: @metatag %>

<%= link_to 'Show', @metatag %> |
<%= link_to 'Back', metatags_path %>

app/views/metatags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Metatags</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Keywords</th>
      <th>Description</th>
      <th>Page</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @metatags.each do |metatag| %>
      <tr>
        <td><%= metatag.title %></td>
        <td><%= metatag.keywords %></td>
        <td><%= metatag.description %></td>
        <td><%= metatag.page %></td>
        <td><%= link_to 'Show', metatag %></td>
        <td><%= link_to 'Edit', edit_metatag_path(metatag) %></td>
        <td><%= link_to 'Destroy', metatag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Metatag', new_metatag_path %>

app/views/metatags/new.html.erb
<h1>New Metatag</h1>

<%= render 'form', metatag: @metatag %>

<%= link_to 'Back', metatags_path %>

app/views/metatags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @metatag.title %>
</p>

<p>
  <strong>Keywords:</strong>
  <%= @metatag.keywords %>
</p>

<p>
  <strong>Description:</strong>
  <%= @metatag.description %>
</p>

<p>
  <strong>Page:</strong>
  <%= @metatag.page %>
</p>

<%= link_to 'Edit', edit_metatag_path(@metatag) %> |
<%= link_to 'Back', metatags_path %>