config/routes.rb
Rails.application.routes.draw do
	
  resources :points
  resources :cities
  resources :contacts
	devise_for :admins
	resources :metatags
	resources :photos
	resources :tours
	root to: 'pages#index'

	get 'closed' => 'pages#closed', as: :closed
	get 'index' => 'pages#index', as: :index
	get 'populars' => 'pages#populars', as: :populars
	get 'results' => 'pages#results', as: :results
	get 'order-form' => 'pages#orderForm', as: :orderForm
	get 'admin' => 'pages#admin', as: :admin
	get 'franchise' => 'pages#landing', as: :franchise
	resources :comments, only: [:new, :create]	
	resources :selections, only: [:new, :create]	

	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :contact
  has_many :points
end

app/models/comment.rb
class Comment < MailForm::Base
	attribute :name, :validate => true
	attribute :phone, :validate => true
	attribute :city, :validate => true
	attribute :mail
	attribute :text, :validate => true

	def headers 
		{
			:subject => "Заявка с сайта франшиза Travel-me.agency",
			:to => "franchise@travel-me.agency",
			:from => %("#{name}" <it@euroukrgroup.com>)
		}
	end
end

app/models/contact.rb
class Contact < ApplicationRecord
	has_many :cities	
	extend FriendlyId
	friendly_id :title, use: :slugged
end

app/models/metatag.rb
class Metatag < ApplicationRecord
end

app/models/photo.rb
class Photo < ApplicationRecord
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/point.rb
class Point < ApplicationRecord
  belongs_to :city
end

app/models/selection.rb
class Selection < MailForm::Base
	attribute :name, :validate => true
	attribute :phone, :validate => true
	attribute :city, :validate => true
	attribute :tour, :validate => true
	attribute :days, :validate => true
	attribute :budget, :validate => true
	attribute :mail
	attribute :text

	def headers 
		{
			:subject => "Подбор тура с сайта Travel-me.agency",
			:to => "info@travel-me.agency",
			:from => %("#{name}" <it@euroukrgroup.com>)
		}
	end
end

app/models/tour.rb
class Tour < ApplicationRecord

	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

	has_attached_file :banner, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :banner, content_type: /\Aimage\/.*\z/

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :authenticate_admin!, only: [:admin]
	layout "landing", only: [:landing]

	def index
		@header = rand(1..2)
		@tours = Tour.all
		@metatags = Metatag.all
	end

	def franchise
		@metatags = Metatag.all
	end

	def admin
		@tours = Tour.all
	end

	def landing
		@comment = Comment.new
	end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :authenticate_admin!, except: [:show]
  before_action :set_tour, only: [:show, :edit, :update, :destroy]

  # GET /tours
  # GET /tours.json
  def index
    @tours = Tour.all
  end

  # GET /tours/1
  # GET /tours/1.json
  def show
  end

  # GET /tours/new
  def new
    @tour = Tour.new
  end

  # GET /tours/1/edit
  def edit
  end

  # POST /tours
  # POST /tours.json
  def create
    @tour = Tour.new(tour_params)

    respond_to do |format|
      if @tour.save
        format.html { redirect_to @tour, notice: 'Tour was successfully created.' }
        format.json { render :show, status: :created, location: @tour }
      else
        format.html { render :new }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tours/1
  # PATCH/PUT /tours/1.json
  def update
    respond_to do |format|
      if @tour.update(tour_params)
        format.html { redirect_to @tour, notice: 'Tour was successfully updated.' }
        format.json { render :show, status: :ok, location: @tour }
      else
        format.html { render :edit }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tours/1
  # DELETE /tours/1.json
  def destroy
    @tour.destroy
    respond_to do |format|
      format.html { redirect_to tours_url, notice: 'Tour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tour
      @tour = Tour.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tour_params
      params.require(:tour).permit(:title, :body, :description, :avatar, :priority, :banner)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/metatags_helper.rb
module MetatagsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="ru">

<head>
  <title>Admin</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= favicon_link_tag %>
  <link href="https://fonts.googleapis.com/css?family=Play" rel="stylesheet">
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'admin', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>

<body>
  <%= render "components/admin/header" %>
  <%= yield %>
</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru">

<head>
	<%= yield :seo %>
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-149538697-1"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag() { dataLayer.push(arguments); }
		gtag('js', new Date());

		gtag('config', 'UA-149538697-1');
	</script>
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<%= favicon_link_tag %>
	<%= yield :head %>
	<link href="https://fonts.googleapis.com/css?family=Play" rel="stylesheet">
	<%= csrf_meta_tags %>
	<%= stylesheet_link_tag    'application', media: 'all' %>
	<%= javascript_include_tag 'application' %>
</head>

<body>
	<% if admin_signed_in? %>
	<%= link_to points_path do %>
	<div class="admin__enter">
		Админ панель
	</div>
	<% end %>
	<% end %>
	<%= yield %>
	<div class="remodal" data-remodal-id="modal">
		<button data-remodal-action="close" class="remodal-close"></button>
		<h1>Подобрать тур онлайн</h1>
		<%= form_for @selection, :html => {class: 'selection-form'} do |f| %>
		<div class="row">
			<div class="col-lg-12">
				<%= f.text_field :name, required: true, placeholder: 'Ваше ФИО', class: "selection-form__input" %>
			</div>
			<div class="col-lg-12">
				<%= f.text_field :phone, required: true, placeholder: 'Ваш номер телефона', class: "selection-form__input" %>
			</div>
			<div class="col-lg-12">
				<%= f.text_field :city, required: true, placeholder: 'Ваш город', class: "selection-form__input" %>
			</div>
			<div class="col-lg-12">
				<%= f.text_field :tour, required: true, placeholder: 'Страна, город, курорт', class: "selection-form__input" %>
			</div>
			<div class="col-lg-12">
				<%= f.text_field :days, required: true, placeholder: 'Количество дней', class: "selection-form__input" %>
			</div>
			<div class="col-lg-12">
				<%= f.text_field :budget, required: true, placeholder: 'Ваш бюджет', class: "selection-form__input" %>
			</div>
			<div class="col-lg-12">
				<%= f.text_field :mail, placeholder: 'Ваш email', class: "selection-form__input" %>
			</div>
			<div class="col-lg-12">
				<%= f.text_area :text, placeholder: ' Ваши пожелания или замечания', class: "selection-form__textarea" %>
			</div>
			<div class="col-lg-12">
				<%=f.submit 'Подать заявку', class: "selection-form__btn"  %>
			</div>
		</div>
		<% end %>
	</div>
</body>
<script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>
<script>
	tinymce.init({
		selector: 'textarea#tour_description'
	});
</script>
<script>
	// open mobile menu
	$('.js-toggle-menu').click(function (e) {
		e.preventDefault();
		$('.mobile-header-nav').slideToggle();
		$(this).toggleClass('open');
	});
</script>

</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html lang="ru">

<head>
  <title>Франшиза сети туристических агентств Travel-Me.Agency</title>
  <meta name="description" content="Купи франшизу туристического агентства Travel-Me.Agency всего за 1 доллар сша.. и открой свой бизнес уже завтра вместе с нами!">
  <meta name="keywords" content="купить франшизу турагентства, турагентство франшиза, открыть турагентство по франшизе, франшиза турагентства цена, 
  франчайзинг туризм, франшизы турагенств, франчайзинг турагентство">
  <meta property="og:image"
    content="https://travel-me.agency/assets/logo2-69b66fa4f7c1cb5bdaf478e4d4a85dbfe36308ef665cab1a9e8aa81d1c4f3825.png" />
  <link rel="canonical" href="<%= request.url %>" itemprop="url">
  <meta property="og:site_name" content="travel-me.agency | TRAVEL-ME.AGENCY">
  <meta property="og:url" content="<%= request.url %>">
  <meta property="og:description" content="Купи франшизу туристического агентства Travel-Me.Agency всего за 1 доллар сша.. и открой свой бизнес уже завтра вместе с нами!">
  <meta property="og:type" content="website">

  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-149538697-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag() { dataLayer.push(arguments); }
    gtag('js', new Date());

    gtag('config', 'UA-149538697-1');
  </script>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= favicon_link_tag %>
  <link href="https://fonts.googleapis.com/css?family=Play" rel="stylesheet">
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'landing', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>

<body>
  <%= yield %>
</body>

</html>

app/views/pages/admin.html.erb
<%= render 'components/header' %>
<div class="admin">  
  <div class="container">
    <div class="row">
      <div class="col-lg-3">
        <%= render "components/adm-menu" %>
      </div>
      <div class="col-lg-9">

        <table class="table table-striped"  >
          <thead>
            <tr>
              <th>Название вакансии</th>
              <th colspan="5"></th>
            </tr>
          </thead>

          <tbody>
            <% @tours.each do |tour| %>
            <tr>
              <td><%= tour.title %></td>
              <td><%= link_to 'Показать', tour %></td>
              <td><%= link_to 'Редактировать', edit_tour_path(tour) %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/pages/closed.html.erb
<title>Сайт на реконструкции...</title>
<div class="coconut">
	<div class="container">
		<div class="row">
			<div class="col-lg-2">
				<div class="logo">
					<%= link_to (image_tag 'logo2.png'), closed_path %>
				</div>
			</div>

			<div class="col-lg-10">
				<div class="tels">
					<ul>
						<li><span>UA:</span> ‎‎+38 044 333 90 45</li>
					</ul>
				</div>

			</div>
			<div class="col-lg-6">
				<div class="trigger-banner">
					<h1>Сайт на реконструкции</h1>
					<h2>Мы скоро вернемся!</h2>

				</div>
			</div>
			<div class="col-lg-6">
				<div class="banner">
					<%= image_tag 'barge.png' %>
				</div>
			</div>
			<div class="col-lg-12">
			</div>
		</div>
	</div>
</div>

app/views/pages/franchise.html.erb
<%= render 'components/headtwo' %>
<section class="franchise">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<h1 class="franchise__h1">
					Купи франшизу всего за 1 доллар сша..
				</h1>
			</div>
			<div class="col-lg-12">
				<h2 class="franchise__h2 text--right">
					..и открой свой бизнес уже завтра вместе с нами!
				</h2>
			</div>
			<div class="col-lg-8 offset--top-l">
				<p class="franchise__p">
					<span class="text--bold">
						TRAVEL ME AGENCY
					</span>
					– cовременная лидирующая международная сеть туристичестких агентств, которая
					активно развивается на территории 8 стран Европейского Союза.
				</p>
				<p class="franchise__p">
					С 2018 года компания запустила продажу собственных франшиз на рынках России, Украины, Белорусии,
					Казахстана и других странах СНГ.
				</p>
				<p class="franchise__p">
					Стать владельцем собственного офиса <span class="text--bold">TRAVEL ME AGENCY</span> теперь может
					каждый из вас.
				</p>
				<p class="franchise__p">
					<span class="text--bold">
						<i>«Мир без границ!»</i>
					</span>
					- главный лозунг компании.
				</p>
				<p class="franchise__p">
					<span class="text--bold">Основные направления</span> деятельности сети агенств <span
						class="text--bold">TRAVEL ME AGENCY:</span>
				</p>
				<ul class="franchise__ul">
					<li class="franchise__li">- Международный туризм</li>
					<li class="franchise__li">- Визовая подержка</li>
					<li class="franchise__li">- Продажа авиа, автобусных, ж/д билетов</li>
					<li class="franchise__li">- Страхование</li>
					<li class="franchise__li">- Аренда авто</li>
					<li class="franchise__li">- Аренда вилл, апартаментов</li>
				</ul>
			</div>
			<div class="col-lg-4">
				<%= image_tag 'logo2.png', class: "franchise__img" %>
				<%= image_tag 'office.jpg', class: "franchise__img" %>
			</div>
		</div>
	</div>
	<div class="propose">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<h2 class="propose__h2 text--center text--bold">
						Окрой свой успешный независимый бизнес, что даст возможность развиваться и получать стабильную
						прибыль за
						счет повышенных комиссий.
					</h2>
				</div>
				<div class="col-lg-12">
					<p class="propose__p">
						Команда специалистов отдела START UP – поможет с открытием офиса «под ключ» с момента подачи
						вашей заявки,
						до момента продажи первого тура, взяв на себя все доверенные обязательства.
					</p>
					<p class="propose__p">
						Приобретая франшизу <span class="text--bold">TRAVEL ME AGENCY</span> вы получаете:
					</p>
					<ul class="propose__ul">
						<li class="propose__li">
							- Полная поддержка специалистами главного офиса в получении всех разрешительных документов
							для
							регистрации юр.лица в кратчайшие сроки
						</li>
						<li class="propose__li">
							- Бухгалтерская и юридическая поддержка
						</li>
						<li class="propose__li">
							- Получение лицензий, банковской гарантии
						</li>
						<li class="propose__li">
							- Контракты со всеми основными действующими туроператорами вашей страны с повышенной
							агентской
							комиссией
						</li>
						<li class="propose__li">
							- Собственный международный корпоративный сайт <a
								href="https://www.travel-me.agency">www.travel-me.agency</a>, с контактами вашего
							офиса
						</li>
						<li class="propose__li">
							- Единый Колл-центр сети
						</li>
						<li class="propose__li">
							- Онлайн системы для поиска туров, аренды недвижимости и авто, страхования
						</li>
						<li class="propose__li">
							- Помошь в поиске будущего офисе в вашем регионе
						</li>
						<li class="propose__li">
							- Бесплатное обучение франчайзи и менеджеров агентства: (собственная школа туризма,
							обучающие семинары по страхованию, вебинары)
						</li>
						<li class="propose__li">
							- Подготовка рекламной и промо компании при открытии офиса
						</li>
						<li class="propose__li">
							- Запуск точки продаж
						</li>
					</ul>
				</div>
				<div class="col-lg-8">
					<p class="propose__p text--bold">
						Требования к франчайзи:
					</p>
					<ul class="propose__ul">
						<li class="propose__li">
							- Собственный, либо арендуемый офис, или островок open space от 5-25 кв.м
						</li>
						<li class="propose__li">
							- Желание иметь свой прибыльный бизнес
						</li>
						<li class="propose__li">
							- Желание учиться
						</li>
						<li class="propose__li">
							- Желание развиваться
						</li>
						<li class="propose__li">
							- Желание быть успешным
						</li>
						<li class="propose__li text--bold">
							- Во всем остальном мы вам поможем!
						</li>
					</ul>
				</div>
				<div class="col-lg-4">
					<%= image_tag 'office.jpg' %>
				</div>
			</div>
		</div>
	</div>
</section>
<section class="buy">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<p class="buy__p">
					Головной BACK OFFICE компании в режиме 24/7 оказывает международную поддержку, консультации
					франчайзи и клиентов официальных точек продаж.
				</p>
				<p class="buy__p">
					Каждый новый офис получает доступ к собственной CRM системе компании, а так же корпоративный сайт.
				</p>
				<p class="buy__p">
					Присоединяясь к <span class="text--bold"> TRAVEL ME AGENCY</span> больше нет ограничений в
					фиксированном количестве туроператоров для
					сотрудничества. Сеть агентств работает со всеми существующими туроператорами вашей страны.
				</p>
				<p class="buy__p">
					Если вы найдете оператора на рынке услуг, с которым мы еще не сотрудничаем – на следующий день
					данный оператор станет нашим новым официальным партнером!
				</p>
				<p class="buy__p buy--red text--bold">
					Стоимость франшизы: (Россия, Украина и в странах СНГ) - 1 $ USD
				</p>
				<p class="buy__p">
					Купить франшизу TRAVEL ME AGENCY теперь возможно и в вашей стране! Позвоните по указанным ниже
					телефонам, наши специалисты с удовольствием проконсультируют более детально вас по всем вопросам
					приобретения франшизы в вашем регионе.
				</p>
				<p class="buy__p">
					Звоните по номерам телефонов:
				</p>
				<a class="buy__phone" href="tel:+380443346319">+38 044 334 63 19 |</a>
				<a class="buy__phone" href="tel:+442080896595">+442 080 89 65 95 |</a>
				‎<a class="buy__phone" href="tel:+74951282039">+7 495 128 20 39</a>
				<p class="buy__p">
					Заявку на звонок, а так же на получение презентации франшизы вы можете оставить, написав письмо на
					корпоративную почту компании: <a
						href="mailto:franchise@travel-me.agency">franchise@travel-me.agency</a>, указав ваше имя,
					страну, регион, номер
					телефона для связи. После чего в кратчайшие сроки с вами свяжется наш специалист по международному
					франчайзингу.
				</p>
			</div>
		</div>
	</div>
</section>
<%= render 'components/footer' %>

app/views/pages/index.html.erb
<div class="island">
	<%= render "components/header" %>
	<div class="container">
		<div class="col-lg-12">
			<h1 class="island__h1">
				Отдыхайте вместе с
				<span class="island__h1--transparent">
					Travel-me.agency
				</span>
			</h1>
		</div>

		<script>
			var osGeo = ''; /* Страна, курорт или отель по умолчанию в форме поиска */
			var osDefaultDeparture = ''; /* ID города или название на языке модуля */
			var osDefaultDuration = ''; /* Начальная длительность в днях */
			var osTarget = ''; /* URL для отправки формы */
			var osContainer = '.results'; /* Элемент DIV, в котором выводить результаты поиска */
			var osTourContainer = '.results'; /* Элемент DIV, в котором выводить подробную информацию о туре */
			var osLang = 'ru'; /* Язык интерфейса (ru|ua) */
			var osTourTargetBlank = true; /* Открывать страницу тура в новом окне? */
			var osOrderUrl = null; /* Вместо формы заказа, переходить на указанный url */
			var osCurrency = 'original'; /* Валюта для вывода туров: converted – гривна, original – в валюте тура $ или € */
		</script>
		<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&subset=cyrillic" rel="stylesheet">
		<link rel="Stylesheet" href="https://export.otpusk.com/os/onsite/form.css" type="text/css" />
		<link rel="Stylesheet" href="https://export.otpusk.com/os/onsite/result.css" type="text/css" />
		<link rel="Stylesheet" href="https://export.otpusk.com/os/onsite/tour.css" type="text/css" />
		<script src="https://export.otpusk.com/api/session?access_token=2ea96-14dc1-928a6-c7625-2cb1e"></script>
		<script src="https://export.otpusk.com/js/onsite/"></script>
		<script src="https://export.otpusk.com/js/order"></script>


	</div>
</div>
<div class="container">
	<div class="results"></div>
</div>
<%= render 'components/hot' %>
<%= render 'components/footer'%>

<% content_for :seo do %>
<title>Сеть туристических агентств Travel Me Agency</title>
<meta name="description" content="Travel Me Agency">
<meta name="keywords" content="туристическое агентство, купить тур">
<meta property="og:image" content="<%= image_url 'og.jpg' %>" />
<link rel="canonical" href="<%= request.url %>" itemprop="url">
<meta property="og:site_name" content="travel-me.agency | TRAVEL ME AGENCY">
<meta property="og:url" content="https://travel-me.agency/">
<meta property="og:description" content="">
<meta property="og:type" content="website">
<% end %>


<script>

	$(".new_f-form-submit").click(function () {
		$(".results").css("padding", "40px 0");
	});

</script>

app/views/pages/index2.html.erb
<div class="island">
	<%= render "components/header" %>
	<div class="container offset--top">
		<div class="search" id="search">
			<script type="text/javascript" language="JavaScript"
				src="//tourclient.ru/f/jsboot/crm155838/find_tour_form?style=full&conf=default"></script>
		</div>
	</div>
</div>
<%# render 'components/choose'%>
<%= render 'components/hot' %>
<%= render 'components/footer'%>

app/views/pages/orderForm.html.erb
<script type="text/javascript" language="JavaScript" src="//tourclient.ru/f/jsboot/crm155838/tour_orderV2?style=default&conf=default"></script>

app/views/pages/populars.html.erb
<div class="island">
  <%= render "components/header" %>
  <div class="container">
    <div class="col-lg-12">
      <h1 class="populars__h1">
        Популярные туры от
        <span class="island__h1--transparent">
          Travel-me.agency
        </span>
      </h1>
    </div>
  </div>
</div>



<section class="populars">
  <link rel="stylesheet" media="screen" href="https://export.otpusk.com/os/hot-module.css" />
  <style>
    .populars {
      margin-top: -215px;
      /* background-color: rgba(255, 255, 255, 0.5); */
    }

    .populars__h1 {
      text-transform: uppercase;
      color: #ffffff;
      text-align: center;
      font-size: 50px;
      padding: 100px 0 270px;
    }

    /* Відступи модуля */
    .os-top-countries {
      padding: 20px 17px 0;
    }

    /* Відступи між колонками */
    .os-top-countries-image ul {
      margin-left: -20px;
    }

    .os-top-countries-image .os-top-countries-item {
      padding-left: 20px;
      margin-bottom: 20px;
      max-width: 240px;
      height: auto;
      position: static;
      float: none;
    }

    .os-top-countries-text .os-top-countries-item {
      padding-left: 26px;
      height: auto;
      position: static;
      float: none;
    }

    .os-top-countries-text ul {
      margin-left: -26px;
    }

    /* Стилі туру */
    .os-top-countries-text .os-top-countries-item {
      margin-bottom: 18px;
      max-width: 287px;
    }

    .os-top-countries-image .os-top-countries-item>a {
      box-shadow: 0 0 5px 1px rgba(0, 0, 0, 0.3);
      -webkit-transition: all .4s;
      -moz-transition: all .4s;
      -o-transition: all .4s;
      transition: all .4s;
    }

    .os-top-countries-image .os-top-countries-item>a:hover {
      -webkit-filter: contrast(1.2);
      filter: contrast(1.2);
    }

    /* Стилі лінії в текстовій версії */
    .os-top-countries-text .os-top-countries-item>a:before {
      top: 14px;
      left: 35px;
      height: 1px;
      background-color: #e1e1e1;
    }

    /* Назва країни */
    .os-top-countries-image .os-top-countries-item .os-country-name {
      color: #fff;
      line-height: 21px;
      font-family: sans-serif;
      font-size: 18px;
      font-weight: 600;
    }

    .os-top-countries-text .os-top-countries-item .os-country-name {
      line-height: 26px;
      font-size: 14px;
      color: #333;
      font-family: sans-serif;
    }

    /* Блок з ціною */
    .os-top-countries-image .os-top-countries-item .os-country-price {
      background-color: #e3505c;
      font-size: 12px;
      color: #fff;
      font-family: sans-serif;
    }

    /* "от" */
    .os-top-countries-text .os-top-countries-item .os-country-price span:nth-child(1) {
      font-size: 10px;
      color: #7e7e7e;
    }

    /* число */
    .os-top-countries-image .os-top-countries-item .os-country-price span:nth-child(2) {
      font-weight: bold;
      font-size: 20px;
    }

    .os-top-countries-text .os-top-countries-item .os-country-price span:nth-child(2) {
      font-size: 16px;
      font-weight: bold;
      line-height: 26px;
      color: #0799ff;
    }

    /* "$/чел." */
    .os-top-countries-text .os-top-countries-item .os-country-price span:nth-child(3) {
      font-size: 14px;
      line-height: 26px;
      color: #0799ff;
      font-weight: 100;
    }

    .os-top-countries-text .os-top-countries-item .os-country-price span:nth-child(2) {
      padding-left: 6px;
    }

    .os-top-countries-text .os-top-countries-item .os-country-price span:nth-child(2),
    .os-top-countries-text .os-top-countries-item .os-country-price span:nth-child(3) {
      background-color: #fff;
      line-height: 26px;
    }

    @media screen and (min-width: 846px) {
      .os-top-countries {
        padding: 40px 17px 0;
      }
    }

    .os-top-countries-item.small .os-country-price span:nth-child(1) {
      top: -2px;
    }

    .os-top-countries-text .os-top-countries-item.small .os-country-price span:nth-child(2) {
      position: relative;
      top: -4px;
      padding-left: 15px;
      font-size: 16px;
    }

    .os-top-countries-text .os-top-countries-item.small .os-country-price span:nth-child(3) {
      position: absolute;
      bottom: 0;
      right: 0;
      line-height: 12px;
      font-size: 12px;
      background-color: transparent;
    }
  </style>

  <script
    src="https://export.otpusk.com/js/top?k=2ea96-14dc1-928a6-c7625-2cb1e&t=image&c=20&u=https://travel-me.agency/&l=ru"></script>

</section>
<%= render 'components/footer' %>